#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLICafeMeo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLICafeMeo")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertMeo(Meo instance);
    partial void UpdateMeo(Meo instance);
    partial void DeleteMeo(Meo instance);
    partial void InsertMon(Mon instance);
    partial void UpdateMon(Mon instance);
    partial void DeleteMon(Mon instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertSuKien(SuKien instance);
    partial void UpdateSuKien(SuKien instance);
    partial void DeleteSuKien(SuKien instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLICafeMeo.Properties.Settings.Default.QLICafeMeoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<Meo> Meos
		{
			get
			{
				return this.GetTable<Meo>();
			}
		}
		
		public System.Data.Linq.Table<Mon> Mons
		{
			get
			{
				return this.GetTable<Mon>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<SuKien> SuKiens
		{
			get
			{
				return this.GetTable<SuKien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_CHI_TIẾT;
		
		private System.Nullable<int> _MÃ_HÓA_ĐƠN;
		
		private System.Nullable<int> _MÃ_MÓN;
		
		private System.Nullable<int> _SỐ_LƯỢNG;
		
		private decimal _ĐƠN_GIÁ;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<Mon> _Mon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_CHI_TIẾTChanging(int value);
    partial void OnMÃ_CHI_TIẾTChanged();
    partial void OnMÃ_HÓA_ĐƠNChanging(System.Nullable<int> value);
    partial void OnMÃ_HÓA_ĐƠNChanged();
    partial void OnMÃ_MÓNChanging(System.Nullable<int> value);
    partial void OnMÃ_MÓNChanged();
    partial void OnSỐ_LƯỢNGChanging(System.Nullable<int> value);
    partial void OnSỐ_LƯỢNGChanged();
    partial void OnĐƠN_GIÁChanging(decimal value);
    partial void OnĐƠN_GIÁChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			this._Mon = default(EntityRef<Mon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ CHI TIẾT]", Storage="_MÃ_CHI_TIẾT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_CHI_TIẾT
		{
			get
			{
				return this._MÃ_CHI_TIẾT;
			}
			set
			{
				if ((this._MÃ_CHI_TIẾT != value))
				{
					this.OnMÃ_CHI_TIẾTChanging(value);
					this.SendPropertyChanging();
					this._MÃ_CHI_TIẾT = value;
					this.SendPropertyChanged("MÃ_CHI_TIẾT");
					this.OnMÃ_CHI_TIẾTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ HÓA ĐƠN]", Storage="_MÃ_HÓA_ĐƠN", DbType="Int")]
		public System.Nullable<int> MÃ_HÓA_ĐƠN
		{
			get
			{
				return this._MÃ_HÓA_ĐƠN;
			}
			set
			{
				if ((this._MÃ_HÓA_ĐƠN != value))
				{
					this.OnMÃ_HÓA_ĐƠNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_HÓA_ĐƠN = value;
					this.SendPropertyChanged("MÃ_HÓA_ĐƠN");
					this.OnMÃ_HÓA_ĐƠNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ MÓN]", Storage="_MÃ_MÓN", DbType="Int")]
		public System.Nullable<int> MÃ_MÓN
		{
			get
			{
				return this._MÃ_MÓN;
			}
			set
			{
				if ((this._MÃ_MÓN != value))
				{
					this.OnMÃ_MÓNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_MÓN = value;
					this.SendPropertyChanged("MÃ_MÓN");
					this.OnMÃ_MÓNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SỐ LƯỢNG]", Storage="_SỐ_LƯỢNG", DbType="Int")]
		public System.Nullable<int> SỐ_LƯỢNG
		{
			get
			{
				return this._SỐ_LƯỢNG;
			}
			set
			{
				if ((this._SỐ_LƯỢNG != value))
				{
					this.OnSỐ_LƯỢNGChanging(value);
					this.SendPropertyChanging();
					this._SỐ_LƯỢNG = value;
					this.SendPropertyChanged("SỐ_LƯỢNG");
					this.OnSỐ_LƯỢNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐƠN GIÁ]", Storage="_ĐƠN_GIÁ", DbType="Money NOT NULL")]
		public decimal ĐƠN_GIÁ
		{
			get
			{
				return this._ĐƠN_GIÁ;
			}
			set
			{
				if ((this._ĐƠN_GIÁ != value))
				{
					this.OnĐƠN_GIÁChanging(value);
					this.SendPropertyChanging();
					this._ĐƠN_GIÁ = value;
					this.SendPropertyChanged("ĐƠN_GIÁ");
					this.OnĐƠN_GIÁChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="MÃ_HÓA_ĐƠN", OtherKey="MÃ_HÓA_ĐƠN", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._MÃ_HÓA_ĐƠN = value.MÃ_HÓA_ĐƠN;
					}
					else
					{
						this._MÃ_HÓA_ĐƠN = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mon_ChiTietHoaDon", Storage="_Mon", ThisKey="MÃ_MÓN", OtherKey="MÃ_MÓN", IsForeignKey=true)]
		public Mon Mon
		{
			get
			{
				return this._Mon.Entity;
			}
			set
			{
				Mon previousValue = this._Mon.Entity;
				if (((previousValue != value) 
							|| (this._Mon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._Mon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._MÃ_MÓN = value.MÃ_MÓN;
					}
					else
					{
						this._MÃ_MÓN = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TÊN_ĐĂNG_NHẬP;
		
		private string _MẬT_KHẨU;
		
		private string _QUYỀN;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTÊN_ĐĂNG_NHẬPChanging(string value);
    partial void OnTÊN_ĐĂNG_NHẬPChanged();
    partial void OnMẬT_KHẨUChanging(string value);
    partial void OnMẬT_KHẨUChanged();
    partial void OnQUYỀNChanging(string value);
    partial void OnQUYỀNChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÊN ĐĂNG NHẬP]", Storage="_TÊN_ĐĂNG_NHẬP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TÊN_ĐĂNG_NHẬP
		{
			get
			{
				return this._TÊN_ĐĂNG_NHẬP;
			}
			set
			{
				if ((this._TÊN_ĐĂNG_NHẬP != value))
				{
					this.OnTÊN_ĐĂNG_NHẬPChanging(value);
					this.SendPropertyChanging();
					this._TÊN_ĐĂNG_NHẬP = value;
					this.SendPropertyChanged("TÊN_ĐĂNG_NHẬP");
					this.OnTÊN_ĐĂNG_NHẬPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MẬT KHẨU]", Storage="_MẬT_KHẨU", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MẬT_KHẨU
		{
			get
			{
				return this._MẬT_KHẨU;
			}
			set
			{
				if ((this._MẬT_KHẨU != value))
				{
					this.OnMẬT_KHẨUChanging(value);
					this.SendPropertyChanging();
					this._MẬT_KHẨU = value;
					this.SendPropertyChanged("MẬT_KHẨU");
					this.OnMẬT_KHẨUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYỀN", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string QUYỀN
		{
			get
			{
				return this._QUYỀN;
			}
			set
			{
				if ((this._QUYỀN != value))
				{
					this.OnQUYỀNChanging(value);
					this.SendPropertyChanging();
					this._QUYỀN = value;
					this.SendPropertyChanged("QUYỀN");
					this.OnQUYỀNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_NhanViens", ThisKey="TÊN_ĐĂNG_NHẬP", OtherKey="TÊN_ĐĂNG_NHẬP")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_HÓA_ĐƠN;
		
		private System.Nullable<System.DateTime> _NGÀY_LẬP;
		
		private System.Nullable<int> _MÃ_NHÂN_VIÊN;
		
		private System.Nullable<int> _MÃ_KHÁCH_HÀNG;
		
		private System.Nullable<decimal> _TỔNG_TIỀN;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_HÓA_ĐƠNChanging(int value);
    partial void OnMÃ_HÓA_ĐƠNChanged();
    partial void OnNGÀY_LẬPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGÀY_LẬPChanged();
    partial void OnMÃ_NHÂN_VIÊNChanging(System.Nullable<int> value);
    partial void OnMÃ_NHÂN_VIÊNChanged();
    partial void OnMÃ_KHÁCH_HÀNGChanging(System.Nullable<int> value);
    partial void OnMÃ_KHÁCH_HÀNGChanged();
    partial void OnTỔNG_TIỀNChanging(System.Nullable<decimal> value);
    partial void OnTỔNG_TIỀNChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ HÓA ĐƠN]", Storage="_MÃ_HÓA_ĐƠN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_HÓA_ĐƠN
		{
			get
			{
				return this._MÃ_HÓA_ĐƠN;
			}
			set
			{
				if ((this._MÃ_HÓA_ĐƠN != value))
				{
					this.OnMÃ_HÓA_ĐƠNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_HÓA_ĐƠN = value;
					this.SendPropertyChanged("MÃ_HÓA_ĐƠN");
					this.OnMÃ_HÓA_ĐƠNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NGÀY LẬP]", Storage="_NGÀY_LẬP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGÀY_LẬP
		{
			get
			{
				return this._NGÀY_LẬP;
			}
			set
			{
				if ((this._NGÀY_LẬP != value))
				{
					this.OnNGÀY_LẬPChanging(value);
					this.SendPropertyChanging();
					this._NGÀY_LẬP = value;
					this.SendPropertyChanged("NGÀY_LẬP");
					this.OnNGÀY_LẬPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ NHÂN VIÊN]", Storage="_MÃ_NHÂN_VIÊN", DbType="Int")]
		public System.Nullable<int> MÃ_NHÂN_VIÊN
		{
			get
			{
				return this._MÃ_NHÂN_VIÊN;
			}
			set
			{
				if ((this._MÃ_NHÂN_VIÊN != value))
				{
					this.OnMÃ_NHÂN_VIÊNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_NHÂN_VIÊN = value;
					this.SendPropertyChanged("MÃ_NHÂN_VIÊN");
					this.OnMÃ_NHÂN_VIÊNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ KHÁCH HÀNG]", Storage="_MÃ_KHÁCH_HÀNG", DbType="Int")]
		public System.Nullable<int> MÃ_KHÁCH_HÀNG
		{
			get
			{
				return this._MÃ_KHÁCH_HÀNG;
			}
			set
			{
				if ((this._MÃ_KHÁCH_HÀNG != value))
				{
					this.OnMÃ_KHÁCH_HÀNGChanging(value);
					this.SendPropertyChanging();
					this._MÃ_KHÁCH_HÀNG = value;
					this.SendPropertyChanged("MÃ_KHÁCH_HÀNG");
					this.OnMÃ_KHÁCH_HÀNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TỔNG TIỀN]", Storage="_TỔNG_TIỀN", DbType="Money")]
		public System.Nullable<decimal> TỔNG_TIỀN
		{
			get
			{
				return this._TỔNG_TIỀN;
			}
			set
			{
				if ((this._TỔNG_TIỀN != value))
				{
					this.OnTỔNG_TIỀNChanging(value);
					this.SendPropertyChanging();
					this._TỔNG_TIỀN = value;
					this.SendPropertyChanged("TỔNG_TIỀN");
					this.OnTỔNG_TIỀNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="MÃ_HÓA_ĐƠN", OtherKey="MÃ_HÓA_ĐƠN")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="MÃ_KHÁCH_HÀNG", OtherKey="MÃ_KHÁCH_HÀNG", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MÃ_KHÁCH_HÀNG = value.MÃ_KHÁCH_HÀNG;
					}
					else
					{
						this._MÃ_KHÁCH_HÀNG = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="MÃ_NHÂN_VIÊN", OtherKey="MÃ_NHÂN_VIÊN", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MÃ_NHÂN_VIÊN = value.MÃ_NHÂN_VIÊN;
					}
					else
					{
						this._MÃ_NHÂN_VIÊN = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_KHÁCH_HÀNG;
		
		private string _HỌ_TÊN;
		
		private string _SỐ_ĐIỆN_THOẠI;
		
		private System.Nullable<int> _ĐIỂM_TÍCH_LŨY;
		
		private bool _ĐÃ_XÓA;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<SuKien> _SuKiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_KHÁCH_HÀNGChanging(int value);
    partial void OnMÃ_KHÁCH_HÀNGChanged();
    partial void OnHỌ_TÊNChanging(string value);
    partial void OnHỌ_TÊNChanged();
    partial void OnSỐ_ĐIỆN_THOẠIChanging(string value);
    partial void OnSỐ_ĐIỆN_THOẠIChanged();
    partial void OnĐIỂM_TÍCH_LŨYChanging(System.Nullable<int> value);
    partial void OnĐIỂM_TÍCH_LŨYChanged();
    partial void OnĐÃ_XÓAChanging(bool value);
    partial void OnĐÃ_XÓAChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._SuKiens = new EntitySet<SuKien>(new Action<SuKien>(this.attach_SuKiens), new Action<SuKien>(this.detach_SuKiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ KHÁCH HÀNG]", Storage="_MÃ_KHÁCH_HÀNG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_KHÁCH_HÀNG
		{
			get
			{
				return this._MÃ_KHÁCH_HÀNG;
			}
			set
			{
				if ((this._MÃ_KHÁCH_HÀNG != value))
				{
					this.OnMÃ_KHÁCH_HÀNGChanging(value);
					this.SendPropertyChanging();
					this._MÃ_KHÁCH_HÀNG = value;
					this.SendPropertyChanged("MÃ_KHÁCH_HÀNG");
					this.OnMÃ_KHÁCH_HÀNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[HỌ TÊN]", Storage="_HỌ_TÊN", DbType="NVarChar(100)")]
		public string HỌ_TÊN
		{
			get
			{
				return this._HỌ_TÊN;
			}
			set
			{
				if ((this._HỌ_TÊN != value))
				{
					this.OnHỌ_TÊNChanging(value);
					this.SendPropertyChanging();
					this._HỌ_TÊN = value;
					this.SendPropertyChanged("HỌ_TÊN");
					this.OnHỌ_TÊNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SỐ ĐIỆN THOẠI]", Storage="_SỐ_ĐIỆN_THOẠI", DbType="NVarChar(20)")]
		public string SỐ_ĐIỆN_THOẠI
		{
			get
			{
				return this._SỐ_ĐIỆN_THOẠI;
			}
			set
			{
				if ((this._SỐ_ĐIỆN_THOẠI != value))
				{
					this.OnSỐ_ĐIỆN_THOẠIChanging(value);
					this.SendPropertyChanging();
					this._SỐ_ĐIỆN_THOẠI = value;
					this.SendPropertyChanged("SỐ_ĐIỆN_THOẠI");
					this.OnSỐ_ĐIỆN_THOẠIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐIỂM TÍCH LŨY]", Storage="_ĐIỂM_TÍCH_LŨY", DbType="Int")]
		public System.Nullable<int> ĐIỂM_TÍCH_LŨY
		{
			get
			{
				return this._ĐIỂM_TÍCH_LŨY;
			}
			set
			{
				if ((this._ĐIỂM_TÍCH_LŨY != value))
				{
					this.OnĐIỂM_TÍCH_LŨYChanging(value);
					this.SendPropertyChanging();
					this._ĐIỂM_TÍCH_LŨY = value;
					this.SendPropertyChanged("ĐIỂM_TÍCH_LŨY");
					this.OnĐIỂM_TÍCH_LŨYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐÃ XÓA]", Storage="_ĐÃ_XÓA", DbType="Bit NOT NULL")]
		public bool ĐÃ_XÓA
		{
			get
			{
				return this._ĐÃ_XÓA;
			}
			set
			{
				if ((this._ĐÃ_XÓA != value))
				{
					this.OnĐÃ_XÓAChanging(value);
					this.SendPropertyChanging();
					this._ĐÃ_XÓA = value;
					this.SendPropertyChanged("ĐÃ_XÓA");
					this.OnĐÃ_XÓAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="MÃ_KHÁCH_HÀNG", OtherKey="MÃ_KHÁCH_HÀNG")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_SuKien", Storage="_SuKiens", ThisKey="MÃ_KHÁCH_HÀNG", OtherKey="MA_KHACH_HANG")]
		public EntitySet<SuKien> SuKiens
		{
			get
			{
				return this._SuKiens;
			}
			set
			{
				this._SuKiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_SuKiens(SuKien entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_SuKiens(SuKien entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Meo")]
	public partial class Meo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_MÈO;
		
		private string _TÊN_MÈO;
		
		private string _GIỐNG_MÈO;
		
		private string _TÌNH_TRẠNG;
		
		private System.Nullable<System.DateTime> _NGÀY_TIÊM_PHÒNG;
		
		private string _GHI_CHÚ;
		
		private bool _ĐÃ_XÓA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_MÈOChanging(int value);
    partial void OnMÃ_MÈOChanged();
    partial void OnTÊN_MÈOChanging(string value);
    partial void OnTÊN_MÈOChanged();
    partial void OnGIỐNG_MÈOChanging(string value);
    partial void OnGIỐNG_MÈOChanged();
    partial void OnTÌNH_TRẠNGChanging(string value);
    partial void OnTÌNH_TRẠNGChanged();
    partial void OnNGÀY_TIÊM_PHÒNGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGÀY_TIÊM_PHÒNGChanged();
    partial void OnGHI_CHÚChanging(string value);
    partial void OnGHI_CHÚChanged();
    partial void OnĐÃ_XÓAChanging(bool value);
    partial void OnĐÃ_XÓAChanged();
    #endregion
		
		public Meo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ MÈO]", Storage="_MÃ_MÈO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_MÈO
		{
			get
			{
				return this._MÃ_MÈO;
			}
			set
			{
				if ((this._MÃ_MÈO != value))
				{
					this.OnMÃ_MÈOChanging(value);
					this.SendPropertyChanging();
					this._MÃ_MÈO = value;
					this.SendPropertyChanged("MÃ_MÈO");
					this.OnMÃ_MÈOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÊN MÈO]", Storage="_TÊN_MÈO", DbType="NVarChar(50)")]
		public string TÊN_MÈO
		{
			get
			{
				return this._TÊN_MÈO;
			}
			set
			{
				if ((this._TÊN_MÈO != value))
				{
					this.OnTÊN_MÈOChanging(value);
					this.SendPropertyChanging();
					this._TÊN_MÈO = value;
					this.SendPropertyChanged("TÊN_MÈO");
					this.OnTÊN_MÈOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GIỐNG MÈO]", Storage="_GIỐNG_MÈO", DbType="NVarChar(50)")]
		public string GIỐNG_MÈO
		{
			get
			{
				return this._GIỐNG_MÈO;
			}
			set
			{
				if ((this._GIỐNG_MÈO != value))
				{
					this.OnGIỐNG_MÈOChanging(value);
					this.SendPropertyChanging();
					this._GIỐNG_MÈO = value;
					this.SendPropertyChanged("GIỐNG_MÈO");
					this.OnGIỐNG_MÈOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÌNH TRẠNG]", Storage="_TÌNH_TRẠNG", DbType="NVarChar(100)")]
		public string TÌNH_TRẠNG
		{
			get
			{
				return this._TÌNH_TRẠNG;
			}
			set
			{
				if ((this._TÌNH_TRẠNG != value))
				{
					this.OnTÌNH_TRẠNGChanging(value);
					this.SendPropertyChanging();
					this._TÌNH_TRẠNG = value;
					this.SendPropertyChanged("TÌNH_TRẠNG");
					this.OnTÌNH_TRẠNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NGÀY TIÊM PHÒNG]", Storage="_NGÀY_TIÊM_PHÒNG", DbType="Date")]
		public System.Nullable<System.DateTime> NGÀY_TIÊM_PHÒNG
		{
			get
			{
				return this._NGÀY_TIÊM_PHÒNG;
			}
			set
			{
				if ((this._NGÀY_TIÊM_PHÒNG != value))
				{
					this.OnNGÀY_TIÊM_PHÒNGChanging(value);
					this.SendPropertyChanging();
					this._NGÀY_TIÊM_PHÒNG = value;
					this.SendPropertyChanged("NGÀY_TIÊM_PHÒNG");
					this.OnNGÀY_TIÊM_PHÒNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GHI CHÚ]", Storage="_GHI_CHÚ", DbType="NVarChar(255)")]
		public string GHI_CHÚ
		{
			get
			{
				return this._GHI_CHÚ;
			}
			set
			{
				if ((this._GHI_CHÚ != value))
				{
					this.OnGHI_CHÚChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHÚ = value;
					this.SendPropertyChanged("GHI_CHÚ");
					this.OnGHI_CHÚChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐÃ XÓA]", Storage="_ĐÃ_XÓA", DbType="Bit NOT NULL")]
		public bool ĐÃ_XÓA
		{
			get
			{
				return this._ĐÃ_XÓA;
			}
			set
			{
				if ((this._ĐÃ_XÓA != value))
				{
					this.OnĐÃ_XÓAChanging(value);
					this.SendPropertyChanging();
					this._ĐÃ_XÓA = value;
					this.SendPropertyChanged("ĐÃ_XÓA");
					this.OnĐÃ_XÓAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mon")]
	public partial class Mon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_MÓN;
		
		private string _TÊN_MÓN;
		
		private System.Nullable<decimal> _GIÁ;
		
		private string _LOẠI;
		
		private bool _NGỪNG_KINH_DOANH;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntitySet<SuKien> _SuKiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_MÓNChanging(int value);
    partial void OnMÃ_MÓNChanged();
    partial void OnTÊN_MÓNChanging(string value);
    partial void OnTÊN_MÓNChanged();
    partial void OnGIÁChanging(System.Nullable<decimal> value);
    partial void OnGIÁChanged();
    partial void OnLOẠIChanging(string value);
    partial void OnLOẠIChanged();
    partial void OnNGỪNG_KINH_DOANHChanging(bool value);
    partial void OnNGỪNG_KINH_DOANHChanged();
    #endregion
		
		public Mon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._SuKiens = new EntitySet<SuKien>(new Action<SuKien>(this.attach_SuKiens), new Action<SuKien>(this.detach_SuKiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ MÓN]", Storage="_MÃ_MÓN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_MÓN
		{
			get
			{
				return this._MÃ_MÓN;
			}
			set
			{
				if ((this._MÃ_MÓN != value))
				{
					this.OnMÃ_MÓNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_MÓN = value;
					this.SendPropertyChanged("MÃ_MÓN");
					this.OnMÃ_MÓNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÊN MÓN]", Storage="_TÊN_MÓN", DbType="NVarChar(100)")]
		public string TÊN_MÓN
		{
			get
			{
				return this._TÊN_MÓN;
			}
			set
			{
				if ((this._TÊN_MÓN != value))
				{
					this.OnTÊN_MÓNChanging(value);
					this.SendPropertyChanging();
					this._TÊN_MÓN = value;
					this.SendPropertyChanged("TÊN_MÓN");
					this.OnTÊN_MÓNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIÁ", DbType="Money")]
		public System.Nullable<decimal> GIÁ
		{
			get
			{
				return this._GIÁ;
			}
			set
			{
				if ((this._GIÁ != value))
				{
					this.OnGIÁChanging(value);
					this.SendPropertyChanging();
					this._GIÁ = value;
					this.SendPropertyChanged("GIÁ");
					this.OnGIÁChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOẠI", DbType="NVarChar(50)")]
		public string LOẠI
		{
			get
			{
				return this._LOẠI;
			}
			set
			{
				if ((this._LOẠI != value))
				{
					this.OnLOẠIChanging(value);
					this.SendPropertyChanging();
					this._LOẠI = value;
					this.SendPropertyChanged("LOẠI");
					this.OnLOẠIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NGỪNG KINH DOANH]", Storage="_NGỪNG_KINH_DOANH", DbType="Bit NOT NULL")]
		public bool NGỪNG_KINH_DOANH
		{
			get
			{
				return this._NGỪNG_KINH_DOANH;
			}
			set
			{
				if ((this._NGỪNG_KINH_DOANH != value))
				{
					this.OnNGỪNG_KINH_DOANHChanging(value);
					this.SendPropertyChanging();
					this._NGỪNG_KINH_DOANH = value;
					this.SendPropertyChanged("NGỪNG_KINH_DOANH");
					this.OnNGỪNG_KINH_DOANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="MÃ_MÓN", OtherKey="MÃ_MÓN")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mon_SuKien", Storage="_SuKiens", ThisKey="MÃ_MÓN", OtherKey="MA_MON")]
		public EntitySet<SuKien> SuKiens
		{
			get
			{
				return this._SuKiens;
			}
			set
			{
				this._SuKiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Mon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Mon = null;
		}
		
		private void attach_SuKiens(SuKien entity)
		{
			this.SendPropertyChanging();
			entity.Mon = this;
		}
		
		private void detach_SuKiens(SuKien entity)
		{
			this.SendPropertyChanging();
			entity.Mon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_NHÂN_VIÊN;
		
		private string _HỌ_TÊN;
		
		private string _GIỚI_TÍNH;
		
		private System.Nullable<System.DateTime> _NGÀY_SINH;
		
		private string _SỐ_ĐIỆN_THOẠI;
		
		private string _CHỨC_VỤ;
		
		private string _TÊN_ĐĂNG_NHẬP;
		
		private bool _ĐÃ_XÓA;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_NHÂN_VIÊNChanging(int value);
    partial void OnMÃ_NHÂN_VIÊNChanged();
    partial void OnHỌ_TÊNChanging(string value);
    partial void OnHỌ_TÊNChanged();
    partial void OnGIỚI_TÍNHChanging(string value);
    partial void OnGIỚI_TÍNHChanged();
    partial void OnNGÀY_SINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGÀY_SINHChanged();
    partial void OnSỐ_ĐIỆN_THOẠIChanging(string value);
    partial void OnSỐ_ĐIỆN_THOẠIChanged();
    partial void OnCHỨC_VỤChanging(string value);
    partial void OnCHỨC_VỤChanged();
    partial void OnTÊN_ĐĂNG_NHẬPChanging(string value);
    partial void OnTÊN_ĐĂNG_NHẬPChanged();
    partial void OnĐÃ_XÓAChanging(bool value);
    partial void OnĐÃ_XÓAChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ NHÂN VIÊN]", Storage="_MÃ_NHÂN_VIÊN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_NHÂN_VIÊN
		{
			get
			{
				return this._MÃ_NHÂN_VIÊN;
			}
			set
			{
				if ((this._MÃ_NHÂN_VIÊN != value))
				{
					this.OnMÃ_NHÂN_VIÊNChanging(value);
					this.SendPropertyChanging();
					this._MÃ_NHÂN_VIÊN = value;
					this.SendPropertyChanged("MÃ_NHÂN_VIÊN");
					this.OnMÃ_NHÂN_VIÊNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[HỌ TÊN]", Storage="_HỌ_TÊN", DbType="NVarChar(100)")]
		public string HỌ_TÊN
		{
			get
			{
				return this._HỌ_TÊN;
			}
			set
			{
				if ((this._HỌ_TÊN != value))
				{
					this.OnHỌ_TÊNChanging(value);
					this.SendPropertyChanging();
					this._HỌ_TÊN = value;
					this.SendPropertyChanged("HỌ_TÊN");
					this.OnHỌ_TÊNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GIỚI TÍNH]", Storage="_GIỚI_TÍNH", DbType="NVarChar(10)")]
		public string GIỚI_TÍNH
		{
			get
			{
				return this._GIỚI_TÍNH;
			}
			set
			{
				if ((this._GIỚI_TÍNH != value))
				{
					this.OnGIỚI_TÍNHChanging(value);
					this.SendPropertyChanging();
					this._GIỚI_TÍNH = value;
					this.SendPropertyChanged("GIỚI_TÍNH");
					this.OnGIỚI_TÍNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[NGÀY SINH]", Storage="_NGÀY_SINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGÀY_SINH
		{
			get
			{
				return this._NGÀY_SINH;
			}
			set
			{
				if ((this._NGÀY_SINH != value))
				{
					this.OnNGÀY_SINHChanging(value);
					this.SendPropertyChanging();
					this._NGÀY_SINH = value;
					this.SendPropertyChanged("NGÀY_SINH");
					this.OnNGÀY_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SỐ ĐIỆN THOẠI]", Storage="_SỐ_ĐIỆN_THOẠI", DbType="NVarChar(20)")]
		public string SỐ_ĐIỆN_THOẠI
		{
			get
			{
				return this._SỐ_ĐIỆN_THOẠI;
			}
			set
			{
				if ((this._SỐ_ĐIỆN_THOẠI != value))
				{
					this.OnSỐ_ĐIỆN_THOẠIChanging(value);
					this.SendPropertyChanging();
					this._SỐ_ĐIỆN_THOẠI = value;
					this.SendPropertyChanged("SỐ_ĐIỆN_THOẠI");
					this.OnSỐ_ĐIỆN_THOẠIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CHỨC VỤ]", Storage="_CHỨC_VỤ", DbType="NVarChar(50)")]
		public string CHỨC_VỤ
		{
			get
			{
				return this._CHỨC_VỤ;
			}
			set
			{
				if ((this._CHỨC_VỤ != value))
				{
					this.OnCHỨC_VỤChanging(value);
					this.SendPropertyChanging();
					this._CHỨC_VỤ = value;
					this.SendPropertyChanged("CHỨC_VỤ");
					this.OnCHỨC_VỤChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÊN ĐĂNG NHẬP]", Storage="_TÊN_ĐĂNG_NHẬP", DbType="NVarChar(50)")]
		public string TÊN_ĐĂNG_NHẬP
		{
			get
			{
				return this._TÊN_ĐĂNG_NHẬP;
			}
			set
			{
				if ((this._TÊN_ĐĂNG_NHẬP != value))
				{
					this.OnTÊN_ĐĂNG_NHẬPChanging(value);
					this.SendPropertyChanging();
					this._TÊN_ĐĂNG_NHẬP = value;
					this.SendPropertyChanged("TÊN_ĐĂNG_NHẬP");
					this.OnTÊN_ĐĂNG_NHẬPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐÃ XÓA]", Storage="_ĐÃ_XÓA", DbType="Bit NOT NULL")]
		public bool ĐÃ_XÓA
		{
			get
			{
				return this._ĐÃ_XÓA;
			}
			set
			{
				if ((this._ĐÃ_XÓA != value))
				{
					this.OnĐÃ_XÓAChanging(value);
					this.SendPropertyChanging();
					this._ĐÃ_XÓA = value;
					this.SendPropertyChanged("ĐÃ_XÓA");
					this.OnĐÃ_XÓAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="MÃ_NHÂN_VIÊN", OtherKey="MÃ_NHÂN_VIÊN")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_TaiKhoan", ThisKey="TÊN_ĐĂNG_NHẬP", OtherKey="TÊN_ĐĂNG_NHẬP", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._TÊN_ĐĂNG_NHẬP = value.TÊN_ĐĂNG_NHẬP;
					}
					else
					{
						this._TÊN_ĐĂNG_NHẬP = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MÃ_PHÒNG;
		
		private string _TÊN_PHÒNG;
		
		private System.Nullable<int> _SỨC_CHỨA;
		
		private string _TRẠNG_THÁI;
		
		private bool _ĐÃ_XÓA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMÃ_PHÒNGChanging(int value);
    partial void OnMÃ_PHÒNGChanged();
    partial void OnTÊN_PHÒNGChanging(string value);
    partial void OnTÊN_PHÒNGChanged();
    partial void OnSỨC_CHỨAChanging(System.Nullable<int> value);
    partial void OnSỨC_CHỨAChanged();
    partial void OnTRẠNG_THÁIChanging(string value);
    partial void OnTRẠNG_THÁIChanged();
    partial void OnĐÃ_XÓAChanging(bool value);
    partial void OnĐÃ_XÓAChanged();
    #endregion
		
		public Phong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MÃ PHÒNG]", Storage="_MÃ_PHÒNG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MÃ_PHÒNG
		{
			get
			{
				return this._MÃ_PHÒNG;
			}
			set
			{
				if ((this._MÃ_PHÒNG != value))
				{
					this.OnMÃ_PHÒNGChanging(value);
					this.SendPropertyChanging();
					this._MÃ_PHÒNG = value;
					this.SendPropertyChanged("MÃ_PHÒNG");
					this.OnMÃ_PHÒNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TÊN PHÒNG]", Storage="_TÊN_PHÒNG", DbType="NVarChar(50)")]
		public string TÊN_PHÒNG
		{
			get
			{
				return this._TÊN_PHÒNG;
			}
			set
			{
				if ((this._TÊN_PHÒNG != value))
				{
					this.OnTÊN_PHÒNGChanging(value);
					this.SendPropertyChanging();
					this._TÊN_PHÒNG = value;
					this.SendPropertyChanged("TÊN_PHÒNG");
					this.OnTÊN_PHÒNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SỨC CHỨA]", Storage="_SỨC_CHỨA", DbType="Int")]
		public System.Nullable<int> SỨC_CHỨA
		{
			get
			{
				return this._SỨC_CHỨA;
			}
			set
			{
				if ((this._SỨC_CHỨA != value))
				{
					this.OnSỨC_CHỨAChanging(value);
					this.SendPropertyChanging();
					this._SỨC_CHỨA = value;
					this.SendPropertyChanged("SỨC_CHỨA");
					this.OnSỨC_CHỨAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TRẠNG THÁI]", Storage="_TRẠNG_THÁI", DbType="NVarChar(50)")]
		public string TRẠNG_THÁI
		{
			get
			{
				return this._TRẠNG_THÁI;
			}
			set
			{
				if ((this._TRẠNG_THÁI != value))
				{
					this.OnTRẠNG_THÁIChanging(value);
					this.SendPropertyChanging();
					this._TRẠNG_THÁI = value;
					this.SendPropertyChanged("TRẠNG_THÁI");
					this.OnTRẠNG_THÁIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ĐÃ XÓA]", Storage="_ĐÃ_XÓA", DbType="Bit NOT NULL")]
		public bool ĐÃ_XÓA
		{
			get
			{
				return this._ĐÃ_XÓA;
			}
			set
			{
				if ((this._ĐÃ_XÓA != value))
				{
					this.OnĐÃ_XÓAChanging(value);
					this.SendPropertyChanging();
					this._ĐÃ_XÓA = value;
					this.SendPropertyChanged("ĐÃ_XÓA");
					this.OnĐÃ_XÓAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuKien")]
	public partial class SuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SUKIEN;
		
		private string _TEN_SUKIEN;
		
		private string _LOAI_KHUYENMAI;
		
		private System.Nullable<int> _MA_MON;
		
		private System.Nullable<int> _MA_KHACH_HANG;
		
		private decimal _GIA_TRI_GIAM;
		
		private string _LOAI_GIAM;
		
		private System.DateTime _NGAY_BATDAU;
		
		private System.DateTime _NGAY_KETTHUC;
		
		private string _TRANG_THAI;
		
		private System.Nullable<bool> _DA_XOA;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<Mon> _Mon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SUKIENChanging(int value);
    partial void OnMA_SUKIENChanged();
    partial void OnTEN_SUKIENChanging(string value);
    partial void OnTEN_SUKIENChanged();
    partial void OnLOAI_KHUYENMAIChanging(string value);
    partial void OnLOAI_KHUYENMAIChanged();
    partial void OnMA_MONChanging(System.Nullable<int> value);
    partial void OnMA_MONChanged();
    partial void OnMA_KHACH_HANGChanging(System.Nullable<int> value);
    partial void OnMA_KHACH_HANGChanged();
    partial void OnGIA_TRI_GIAMChanging(decimal value);
    partial void OnGIA_TRI_GIAMChanged();
    partial void OnLOAI_GIAMChanging(string value);
    partial void OnLOAI_GIAMChanged();
    partial void OnNGAY_BATDAUChanging(System.DateTime value);
    partial void OnNGAY_BATDAUChanged();
    partial void OnNGAY_KETTHUCChanging(System.DateTime value);
    partial void OnNGAY_KETTHUCChanged();
    partial void OnTRANG_THAIChanging(string value);
    partial void OnTRANG_THAIChanged();
    partial void OnDA_XOAChanging(System.Nullable<bool> value);
    partial void OnDA_XOAChanged();
    #endregion
		
		public SuKien()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._Mon = default(EntityRef<Mon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SUKIEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SUKIEN
		{
			get
			{
				return this._MA_SUKIEN;
			}
			set
			{
				if ((this._MA_SUKIEN != value))
				{
					this.OnMA_SUKIENChanging(value);
					this.SendPropertyChanging();
					this._MA_SUKIEN = value;
					this.SendPropertyChanged("MA_SUKIEN");
					this.OnMA_SUKIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_SUKIEN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_SUKIEN
		{
			get
			{
				return this._TEN_SUKIEN;
			}
			set
			{
				if ((this._TEN_SUKIEN != value))
				{
					this.OnTEN_SUKIENChanging(value);
					this.SendPropertyChanging();
					this._TEN_SUKIEN = value;
					this.SendPropertyChanged("TEN_SUKIEN");
					this.OnTEN_SUKIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_KHUYENMAI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LOAI_KHUYENMAI
		{
			get
			{
				return this._LOAI_KHUYENMAI;
			}
			set
			{
				if ((this._LOAI_KHUYENMAI != value))
				{
					this.OnLOAI_KHUYENMAIChanging(value);
					this.SendPropertyChanging();
					this._LOAI_KHUYENMAI = value;
					this.SendPropertyChanged("LOAI_KHUYENMAI");
					this.OnLOAI_KHUYENMAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MON", DbType="Int")]
		public System.Nullable<int> MA_MON
		{
			get
			{
				return this._MA_MON;
			}
			set
			{
				if ((this._MA_MON != value))
				{
					if (this._Mon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_MONChanging(value);
					this.SendPropertyChanging();
					this._MA_MON = value;
					this.SendPropertyChanged("MA_MON");
					this.OnMA_MONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KHACH_HANG", DbType="Int")]
		public System.Nullable<int> MA_KHACH_HANG
		{
			get
			{
				return this._MA_KHACH_HANG;
			}
			set
			{
				if ((this._MA_KHACH_HANG != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_KHACH_HANGChanging(value);
					this.SendPropertyChanging();
					this._MA_KHACH_HANG = value;
					this.SendPropertyChanged("MA_KHACH_HANG");
					this.OnMA_KHACH_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_TRI_GIAM", DbType="Decimal(18,2) NOT NULL")]
		public decimal GIA_TRI_GIAM
		{
			get
			{
				return this._GIA_TRI_GIAM;
			}
			set
			{
				if ((this._GIA_TRI_GIAM != value))
				{
					this.OnGIA_TRI_GIAMChanging(value);
					this.SendPropertyChanging();
					this._GIA_TRI_GIAM = value;
					this.SendPropertyChanged("GIA_TRI_GIAM");
					this.OnGIA_TRI_GIAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_GIAM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LOAI_GIAM
		{
			get
			{
				return this._LOAI_GIAM;
			}
			set
			{
				if ((this._LOAI_GIAM != value))
				{
					this.OnLOAI_GIAMChanging(value);
					this.SendPropertyChanging();
					this._LOAI_GIAM = value;
					this.SendPropertyChanged("LOAI_GIAM");
					this.OnLOAI_GIAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_BATDAU", DbType="Date NOT NULL")]
		public System.DateTime NGAY_BATDAU
		{
			get
			{
				return this._NGAY_BATDAU;
			}
			set
			{
				if ((this._NGAY_BATDAU != value))
				{
					this.OnNGAY_BATDAUChanging(value);
					this.SendPropertyChanging();
					this._NGAY_BATDAU = value;
					this.SendPropertyChanged("NGAY_BATDAU");
					this.OnNGAY_BATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_KETTHUC", DbType="Date NOT NULL")]
		public System.DateTime NGAY_KETTHUC
		{
			get
			{
				return this._NGAY_KETTHUC;
			}
			set
			{
				if ((this._NGAY_KETTHUC != value))
				{
					this.OnNGAY_KETTHUCChanging(value);
					this.SendPropertyChanging();
					this._NGAY_KETTHUC = value;
					this.SendPropertyChanged("NGAY_KETTHUC");
					this.OnNGAY_KETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="NVarChar(50)")]
		public string TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this.OnTRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI = value;
					this.SendPropertyChanged("TRANG_THAI");
					this.OnTRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA_XOA", DbType="Bit")]
		public System.Nullable<bool> DA_XOA
		{
			get
			{
				return this._DA_XOA;
			}
			set
			{
				if ((this._DA_XOA != value))
				{
					this.OnDA_XOAChanging(value);
					this.SendPropertyChanging();
					this._DA_XOA = value;
					this.SendPropertyChanged("DA_XOA");
					this.OnDA_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_SuKien", Storage="_KhachHang", ThisKey="MA_KHACH_HANG", OtherKey="MÃ_KHÁCH_HÀNG", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.SuKiens.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.SuKiens.Add(this);
						this._MA_KHACH_HANG = value.MÃ_KHÁCH_HÀNG;
					}
					else
					{
						this._MA_KHACH_HANG = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mon_SuKien", Storage="_Mon", ThisKey="MA_MON", OtherKey="MÃ_MÓN", IsForeignKey=true)]
		public Mon Mon
		{
			get
			{
				return this._Mon.Entity;
			}
			set
			{
				Mon previousValue = this._Mon.Entity;
				if (((previousValue != value) 
							|| (this._Mon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mon.Entity = null;
						previousValue.SuKiens.Remove(this);
					}
					this._Mon.Entity = value;
					if ((value != null))
					{
						value.SuKiens.Add(this);
						this._MA_MON = value.MÃ_MÓN;
					}
					else
					{
						this._MA_MON = default(Nullable<int>);
					}
					this.SendPropertyChanged("Mon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
